#!/bin/bash

# aplicaciones por defecto
export EDITOR="nvim"
export GIT_EDITOR="nvim"
export TERMINAL="alacritty"

# paths
export PATH="$HOME/scripts:$PATH"
export PATH="$HOME/go/bin:$PATH"

# monitores
export monitor0="eDP-1" 
export monitor1="DP-2-2"
export monitor2="DP-2-1"

# colores
