#!/bin/bash

# archivos que se respaldaran

# init.vim (neovim) ~/.config/nvim/init.vim

# config (i3) ~/.config/i3/config

# .Xresouces (urxvt)  ~/.Xresources

cp ~/.config/nvim/init.vim ~/DotFiles

cp ~/.config/i3/config ~/DotFiles

cp ~/.Xresources ~/DotFiles
