#!/bin/bash

# archivos que se respaldaran

# init.vim (neovim) ~/.config/nvim/init.vim

# config (i3) ~/.config/i3/config

# .Xresources (urxvt)  ~/.Xresources


argumento='-'$1

neovim="neovim"
neovim_path="~/.config/nvim/"

i3="i3"
i3_path="~/.config/i3/"

urxvt="urxvt"
urxvt_path="~/"

get_dot_files(){
    mkdir neovim
    cp ~/.config/nvim/init.vim ~/DotFiles/$neovim # neovim
    
    mkdir i3
    cp ~/.config/i3/config ~/DotFiles/$i3 # i3-gaps
    
    mkdir urxvt
    cp ~/.Xresources ~/DotFiles/$urxvt # urxvt

    mkdir polybar
    cp ~/.config/polybar/config ~/DotFiles/polybar
    

    return
}

set_dot_files(){

    cp  ~/DotFiles/$neovim/init.vim $neovim_path # neovim

    cp ~/DotFiles/$i3/config ~/.config/i3/ # i3-gaps

    cp ~/Dotfiles/$urxvt/.Xresources ~/

    cp ~/DotFiles/polybar/config ~/.config/polybar

    return
}

usage(){
    echo "DotHelper [options] "
    echo " "
    echo "-h help"
    echo "-b backup dot files"
    echo "-s set dot files"

}


if [ $argumento = "--b" ] 
then

get_dot_files


elif [ $argumento = "--s" ] 
then

set_dot_files

else
    usage
fi

    
    

