#!/bin/bash


dataBaseList=~/DotFiles/DotDataBaseList
DotDataBase=~/DotFiles/DotDataBase

function setDots() {
    archivosYCarpetas=$(find $DotDataBase -mindepth 1 -print)
    for i in $archivosYCarpetas; do
        elemento=$(echo $i | sed "s|/DotFiles/DotDataBase||")
        if [ -d $i ]; then
            echo "mk dir $elemento"
        else
            echo "copiar desde $i a $elemento"
        fi
    done
}
function ayuda() {
    echo "uso:"
    echo "  DotMaid -[opcion] [archivo?]"
    echo "  opciones:"
    echo "                -a: Copia los dotfiles a la base de datos"
    echo "                -h: muestra esta ayuda"
    echo "                -s: Colocar los dotfiles en el lugar de destino"
    echo "                -u: actualiza los dotfiles a la base de datos"
}
function addDots() {
    # recibe un argumento $1 con la ruta relativa
    # del archivo o directorio a agregar a la base de datos
    # ruta absoluta del archivo o carpeta

    # ruta absoluta al archivo o directorio con tilde expandida
    path2file=$(echo $1 | sed "s|~|$HOME|")
    # ruta completa con /home/USER remplazado con "~"
    fullPath="$(readlink -f $path2file | sed "s|$HOME|~|")" 

    # buscar si eldot file ya fue añadido a la base de datos
    if [ "$(grep -F $fullPath $dataBaseList)" == "$fullPath" ]
    then
        echo "Actualizando $1"
    else
        # agregar ruta absoluta a la base de datos
        echo $fullPath >> $dataBaseList
    fi

    # obtener la ultima carpeta del archivo o carpeta
    lastFolderRelativePath="$(dirname $fullPath | cut -c2-)"

    # crear carpetas de destino
    mkdir -p $DotDataBase$lastFolderRelativePath

    # expandir tilde "~"
    fullPath=$(echo $fullPath | sed "s|~|$HOME|")
    # copiar archivos a destino
    cp -r $fullPath $DotDataBase$lastFolderRelativePath
}
function updateDots() {
    # hacer una lista con los dotfiles de la base de datos
    allDots=$(cat $dataBaseList)

    # para cada dotfile llamar la funcion addDots
    for dotFile in $allDots
    do 
        f=$(echo $dotFile | sed "s|~|$HOME|")
        if [ -a $f ]; then
            addDots $f
        fi
    done
}
if [ "$1" == "-s" ]
then
    echo "Colocar los dotfiles en el lugar de destino"
    setDots "$2"
elif [ "$1" == "-a" ]
then
    echo "Copia los dotfiles a la base de datos"
    addDots "$2"
elif [ "$1" == "-u" ]
then
    updateDots
elif [ "$1" == "-h" ] || [ "$1" == "--help" ] || [ "$1" == "" ]
then
    ayuda
else
    ayuda
fi
