#!/bin/bash

currentDir=$(pwd)
dotpath="$currentDir/dotdb"

# create directories
for path in $(find $dotpath | sed '1d'); do
    if [ -d $path ]; then
        mkdir -p $(echo $path | sed "s|$dotpath|$HOME|g")
    fi
done

# copy dotfiles

for path in $(find $dotpath | sed '1d'); do
    if [ -f  $path ]; then
        cp -r $path $(echo $path | sed "s|$dotpath|$HOME|g")
    fi
done
