#!/bin/bash
# vars
. $HOME/.config/vars

#hotkeys
killall sxhkd; sxhkd &

# limpiar reglas al reiniciar 
bspc rule -r "*"

# polybar
~/.config/polybar/launch.sh

# integración con gnome
/usr/lib/gsd-xsettings
gnome-power-manager
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
gnome-flashback
gsettings set org.gnome.gnome-flashback desktop false

if [ ! -f /tmp/currentDockState ]; then
    dockstate -a
fi

dockmode last

# llenar monitores vacios
bmm -f

# eliminar desktops vacios
bmm -d

# acciones a ejecutar cuando bspwm muta
killall autoDesktopClean; autoDesktopClean &

bspc config border_width         2
bspc config normal_border_color "#222"
bspc config active_border_color "#555"
bspc config window_gap          12
bspc config top_padding         35

bspc config split_ratio          0.52
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'

# aplicaciones al inicio

# fondo de pantalla
feh --bg-fill ~/multimedia/imagenes/wallpapers/wall.*

# reiniciar las aplicaciones
killall picom; picom &
