#! /bin/sh

# limpiar reglas al reiniciar 
bspc rule -r "*"

# aplicaciones al inicio

# reiniciar las aplicaciones
killall sxhkd; sxhkd &
killall picom; picom &

# polybar
~/.config/polybar/launch.sh

# fondo de pantalla
feh --bg-fill ~/multimedia/img/wall/minimal-mojave-day-gi.jpg

# integración con gnome
/usr/lib/gsd-xsettings
gnome-power-manager
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
gnome-flashback
gsettings set org.gnome.gnome-flashback desktop false

# monitores
bspc monitor DisplayPort-0 -d 1 2 3 4 
bspc monitor DisplayPort-1 -d 5 6 7 8 

bspc config border_width         2
bspc config normal_border_color "#222"
bspc config active_border_color "#555"
bspc config window_gap          12
bspc config top_padding         30

bspc config split_ratio          0.52
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
