#!/bin/bash
dock(){
    # set audio output to hdmi screen
    pactl set-card-profile 0 output:hdmi-stereo-extra1+input:analog-stereo
    
    # set xrandr to output to external screens
    bash $HOME/.screenlayout/dock.sh

    # send bspwm desktops to dock screens
    bmm -rs

    echo "docked" > /tmp/currentDockState

    sleep 1
    $HOME/.config/polybar/launch.sh
    
    # llenar monitores vacios
    bmm -f
}
undock(){
    # set audio output to internal speaker
    pactl set-card-profile 0 output:analog-stereo+input:analog-stereo

    # set xrandr to output to internal screen
    bash $HOME/.screenlayout/laptop.sh

    # send all desktops to laptop

    if [ $(cat /tmp/currentDockState) = "docked" ]; then
        rm /tmp/bmm/*
        bmm -s
    fi
    bmm -M
    echo "undocked" > /tmp/currentDockState
}
last(){
    if [ "$(cat /tmp/currentDockState)" = "docked" ];then
        dock
    else
        undock
    fi
}

while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
        dock)
        shift
        dock
        ;;
        undock)
        shift
        undock
        ;;
        last)
        shift
        last
        ;;
    esac
    shift
done
