#!/bin/bash

paths="~/scripts/programs/g/g $HOME"
if [ "$1" == "--bookmarks" ]; then
    paths="cat $HOME/.data/g/bookmarks | sort"
fi

path=$(exec $paths | grep -v "^\s*$"| fzf)

[[ ! -z "$path" ]] && cd $path
clear
exa
$SHELL
