#!/bin/bash
# prints thw current network speed 
# also can get the currently used network card

networkCardInUse() {
    echo $(ip route get "1.1.1.1" 2>/dev/null | grep -Po '(?<=(dev )).*(?= src| proto)')
}

#default config
interface=$( networkCardInUse )


t="1"

upsufix=""
downsufix=""

# parse arguments
while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
        -i)
        shift
        interface="$1"
        ;;
        --upsufix)
        shift
        upsufix="$1"
        ;;
        --downsufix)
        shift
        downsufix="$1"
        ;;
        -t)
        shift
        t="$1"
        ;;
        -pi)
        echo $interface
        exit
        ;;
        *)
        shift
        ;;
    esac
done

# if no interface
if [ -z $interface ];then
    echo "No conection"
    exit
fi

tm=$(awk "BEGIN {print 1/$t}")

# down
fr=$(cat /proc/net/dev | grep $interface | awk '{print $10}')
# up
fs=$(cat /proc/net/dev | grep $interface | awk '{print $2}')

sleep $tm

# down
sr=$(cat /proc/net/dev | grep $interface | awk '{print $10}')
# up
ss=$(cat /proc/net/dev | grep $interface | awk '{print $2}')

# speed per second

up=$((( $sr - $fr ) * $t))
down=$((( $ss - $fs ) * $t))
ups=$(echo $up | numfmt --to=iec-i --suffix=B/s  --padding 8)
downs=$(echo $down | numfmt --to=iec-i --suffix=B/s --padding 8)


echo "$ups$upsufix $downs$downsufix"
